{% set name = "exchange-calendars" %}
{% set version = "4.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/exchange_calendars-{{ version }}.tar.gz
  sha256: 6f80512de85b5750caf18f2e17e40d68acde0500e20d952d445377bb367c7209

build:
  entry_points:
    - ecal = exchange_calendars.ecal:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm >=6.2
  run:
    - korean_lunar_calendar
    - numpy
    - pandas >=1.1
    - pyluach
    - python >=3.8
    - python-dateutil
    - pytz
    - toolz

test:
  imports:
    - exchange_calendars
  commands:
    - pip check
    - ecal XNYS 2020
  requires:
    - pip

about:
  home: https://github.com/gerrymanoim/exchange_calendars
  summary: exchange_calendars is a Python library with securities exchange calendars
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stefan-jansen
    - yehoshuadimarsky
